version: '3'
services:
  php:
    image: php:8.2-fpm-alpine
    container_name: app-php
    volumes:
      - ./:/var/www

  db:
    image: mysql:8
    container_name: app-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    # остальные настройки наследуются

  nginx:
    ports:
      # Переопределение портов осуществляется извне.
      - "${NGINX_HTTP_PORT:-8090}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    name: app-network
    driver: bridge
